import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const adobeGaramondPro = localFont({
  src: [
    { path: "./fonts/Adobe Garamond Pro Regular.woff2", weight: "400" },
    { path: "./fonts/Adobe Garamond Pro Italic.woff2", weight: "400", style: "italic" },
    { path: "./fonts/Adobe Garamond Pro Bold.woff2", weight: "700" },
    { path: "./fonts/Adobe Garamond Pro Bold Italic.woff2", weight: "700", style: "italic" },
    { path: "./fonts/Adobe Garamond Pro Semibold.woff2", weight: "600" },
    { path: "./fonts/Adobe Garamond Pro Semibold Italic.woff2", weight: "600", style: "italic" },
  ],
  variable: "--font-adobe-garamond",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${adobeGaramondPro.variable} font-sans antialiased bg-black`}
      >
        {children}
      </body>
    </html>
  );
}
